---
- name: Machine setup
  hosts: all
  tags: always
  connection: local
  gather_facts: true
  become: true
  vars_files:
    - /vars/Archlinux.yml

  pre_tasks:
    - name: Pre-run | update package cache arch
      tags: always
      community.general.pacman: update_cache=yes
      changed_when: false
      when: ansible_distribution == "Archlinux"


- hosts: All
  tags: base
  become: true
  roles:
    - base

#- hosts: workstation
#  tags: workstation
#  become: true
#  roles:
#    - workstation

