- name: System setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    name:
      - curl
      - htop
      - iotop
      - mc
      - mosh
      - net-tools
      - nmap
      - rsync
      - tar
      - traceroute
      - wget
      - whois
      - zsh
    state: latest

- name: System setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  ansible.builtin.package:
    name:
      - man-db
      - man-pages
    state: latest
