- name: System setup | prerequisits packages | install packages
  tags: git, development, sound, fonts
  ansible.builtin.package:
    name:
      - git
      - base-devel
      - pipewire
      - wireplumber
      - pamixer
      - brightnessctl
      - sddm
      - ttf-cascadia-code-nerd
      - ttf-cascadia-mono-nerd
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-fira-sans
      - ttf-firacode-nerd
      - ttf-iosevka-nerd
      - ttf-iosevkaterm-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-jetbrains-mono
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-mono
    state: latest

- name: Install yay using makepkg if it isn't installed already 
  kewlfft.aur.aur: 
    name: yay 
    use: makepkg 
    state: present 
  become: yes 
  become_user: aur_builder

- name: Upgrade the system using yay, only act on AUR packages.
  kewlfft.aur.aur:
    upgrade: yes
    aur_only: yes
