  - name: System setup | core packages | install hyprland packages and dependencies
    tags: hyprland
    ansible.builtin.package:
      name:
        - hyprland
        - xdg-desktop-portal-hyprland
        - qt5-wayland
        - qt6-wayland
        - waybar
        - cliphist
        - polkit-kde-agent
        - dunst
      state: latest

  - name: System configuration | core packages | create hyprland folder
    tags: copy hyprland.conf
    ansible.builtin.file:
      path: '/home/{{ username_on_the_host.stdout }}/.config/hypr'
      state: directory
      mode: 0755
      owner: '{{ username_on_the_host.stdout }}'
      group: '{{ username_on_the_host.stdout }}'

  - name: System configuration | core packages | copy hyprland config files
    tags: copy hyprland.conf
    ansible.builtin.copy:
      src: /usr/share/hypr/hyprland.conf
      dest: '/home/{{ username_on_the_host.stdout }}/.config/hypr/hyprland.conf'
      force: true

  - name: System configuration | core packages | configuration files
    tags: hyprland
    ansible.builtin.lineinfile:
        dest: '/home/{{ username_on_the_host.stdout }}/.config/hypr/hyprland.conf'
        regexp: '^#?autogenerated'
        state: absent
    when: ansible_distribution == 'Archlinux'

  - name: System configuration | core packages | copy waybar config files
    tags: copy waybar config
    ansible.builtin.copy:
      src: /etc/xdg/waybar
      dest: '/home/{{ username_on_the_host.stdout }}/.config/'
      mode: 0755
      owner: '{{ username_on_the_host.stdout }}'
      group: '{{ username_on_the_host.stdout }}'
      force: true
