- name: System setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    state: latest
    name:
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - mc
      - mosh
      - net-tools
      - nmap
      - rsync
      - tar
      - tmux
      - traceroute
      - wget
      - whois
      - zsh

- name: System setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  ansible.builtin.package:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
