- name: system setup | application packages | install packages | pacman
  tags: terminal, editors and so on
  nsible.builtin.package:
    name:
      - fish
      - nano      
    state: latest

- name: system setup | application packages | install packages | yay
  kewlfft.aur.aur:
    name: brave-bin
    state: latest
  become: yes
  become_user: aur_builder