- name: system setup | application packages | install packages | pacman
  tags: terminal, editors and so on
  ansible.builtin.package:
    name:
      - fish
      - nano      
    state: latest

#- name: Upgrade the system using yay, only act on AUR packages.
#  kewlfft.aur.aur:
#    upgrade: yes
#    use: yay
#    aur_only: yes

- name: system setup | application packages | install packages | yay
  kewlfft.aur.aur:
    name: brave-bin
    state: latest
  become: true
  become_user: aur_builder
