- name: System setup | prerequisits packages | install packages
  tags: sound, control, fonts
  ansible.builtin.package:
    name:
      - pipewire
      - wireplumber
      - pamixer
      - brightnessctl
      - ttf-cascadia-code-nerd ttf-cascadia-mono-nerd ttf-fira-code ttf-fira-mono ttf-fira-sans ttf-firacode-nerd ttf-iosevka-nerd ttf-iosevkaterm-nerd ttf-jetbrains-mono-nerd ttf-jetbrains-mono ttf-nerd-fonts-symbols ttf-nerd-fonts-symbols ttf-nerd-fonts-symbols-mono
    state: latest
