- name: System setup | repositories | add ignored packages for archlinux hosts
  tags: packages,repositories
  ansible.builtin.lineinfile:
      dest: /etc/pacman.conf
      regexp: "^#?IgnorePkg"
      line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers"
  when: ansible_distribution == "Archlinux"
