- name: Update all non-AUR packages
  ansible.builtin.package:
    update_cache: yes
    upgrade: yes

- name: Ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  ansible.builtin.package:
    name: ansible
    state: latest

- name: Ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  ansible.builtin.package:
    name:
      - "{{ dconf_package }}"
      - "{{ python_psutil_package }}"

- name: Ansible setup | create aur user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Ansible setup | Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: 0644
    validate: 'visudo -cf %s'

- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host
