- name: Cleanup | remove aur_builder from sudoers
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    state: absent

- name: Cleanup | remove user ur_builder
  become: true
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: true
