# Load distro-specific variables
- name: Including vars
  ansible.builtin.import_tasks: "Archlinux.yml"
  tags: always

- name: Starting main block
  block:
    # Set up the ansible environment
    - name: Set up the ansible environment
      ansible.builtin.import_tasks: ansible_setup.yml

    # install software
    - name: Configuring repos
      ansible.builtin.import_tasks: software/repositories.yml

    - name: Install software for development
      ansible.builtin.import_tasks: software/packages_development.yml

    - name: Install software prerequisites
      ansible.builtin.import_tasks: software/packages_prerequisites.yml

    - name: Install software utilities
      ansible.builtin.import_tasks: software/packages_utilities.yml

    - name: Install software applications
      ansible.builtin.import_tasks: software/packages_applications.yml


    # Perform remaining tasks:
    - name: Clock tasks
      ansible.builtin.import_tasks: system_setup/clock.yml
    - name: Cron tasks
      ansible.builtin.import_tasks: system_setup/cron.yml
    - name: Logging tasks
      ansible.builtin.import_tasks: system_setup/logging.yml
    - name: Openssh tasks
      ansible.builtin.import_tasks: system_setup/openssh.yml
    - name: Scripts tasks
      ansible.builtin.import_tasks: system_setup/scripts.yml

    - name: Cleanup
      ansible.builtin.import_tasks: cleanup.yml

  rescue:
    - name: Rescue task
      ansible.builtin.set_fact: task_failed=true
