# Load distro-specific variables
- name: Including vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Starting main block
  block:
    # Set up the ansible environment
    - name: Set up the ansible environment
      ansible.builtin.import_tasks: ansible_setup.yml

    # install software
    - name: Configuring repos
      ansible.builtin.import_tasks: software/repositories.yml

    - name: Install prerequisites
      ansible.builtin.import_tasks: software/configuration_prerequisites.yml

    - name: Install core
      ansible.builtin.import_tasks: software/configuration_core.yml

    - name: Install applications
      ansible.builtin.import_tasks: software/configuration_applications.yml

    - name: Basic configuration
      ansible.builtin.import_tasks: software/configuration_config.yml

    - name: Install utilities
      ansible.builtin.import_tasks: software/configuration_utilities.yml


    # Perform remaining tasks:
    - name: Clock tasks
      ansible.builtin.import_tasks: system_setup/clock.yml
    - name: Cron tasks
      ansible.builtin.import_tasks: system_setup/cron.yml
    - name: Logging tasks
      ansible.builtin.import_tasks: system_setup/logging.yml
    - name: Openssh tasks
      ansible.builtin.import_tasks: system_setup/openssh.yml
    - name: Scripts tasks
      ansible.builtin.import_tasks: system_setup/scripts.yml

    - name: Cleanup
      ansible.builtin.import_tasks: cleanup.yml

  rescue:
    - name: Print when errors
      ansible.builtin.set_fact:
        task_failed: true
