# Load distro-specific variables
- name: Including vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Starting main block
  block:
    # Set up the ansible environment
    - name: Set up the ansible environment
      import_tasks: ansible_setup.yml

    # install software
    - name: Install software
      import_tasks: software/repositories.yml
      import_tasks: software/packages_development.yml
      import_tasks: software/packages_utilities.yml

    # Perform remaining tasks:
    - name: Perform remaining tasks
      import_tasks: system_setup/clock.yml
      import_tasks: system_setup/cron.yml
      import_tasks: system_setup/logging.yml
      import_tasks: system_setup/openssh.yml
      import_tasks: system_setup/scripts.yml
    
    - name: Cleanup
      import_tasks: cleanup.yml

    - name: Rescue
      rescue:
      - set_fact: task_failed=true