- name: System setup | cron | install cron package
  tags: packages,cron
  ansible.builtin.package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: System setup | cron | start and enable cronie daemon
  tags: cron
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"
