- name: System setup | openssh | install or update daemon package
  tags: openssh,ssh,system,settings
  ansible.builtin.package:
    name: "{{ openssh_package }}"
    state: latest
  notify: restart_sshd

- name: System setup | openssh | enable daemon
  tags: openssh,ssh,system,settings
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    enabled: true
    state: started
